services:
  postgresql:
    image: postgres:latest
    container_name: postgres-store
    network_mode: host
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=store
      - TZ=Etc/UTC

