version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgres-loja
    network_mode: host
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=loja
      - TZ=Etc/UTC